server:
  port: 8080


raijin:
  enable_programmatic_mapping: false
  tracing:
    enabled: false
  mappings:
    -
      name: raijin_route
      host: raijin.itachi-v2.local
      destinations: httpbin.org
    -
      name: account_route
      host: account.itachi-v2.local
      destinations: localhost:8081
    -
      name: company_route
      host: company.itachi-v2.local
      destinations: localhost:8082
    -
      name: ical_route
      host: ical.itachi-v2.local
      destinations: localhost:8083
    -
      name: whoami_route
      host: whoami.itachi-v2.local
      destinations: localhost:8084
      timeout:
        connect: 10000
        read: 10000
    -
      name: superpowers_route
      host: superpowers.itachi-v2.local
      destinations: localhost:8085
    -
      name: www_route
      host: www.itachi-v2.local
      destinations: localhost:8086
    -
      name: myaccount_route
      host: myaccount.itachi-v2.local
      destinations: localhost:9000
    -
      name: app_route
      host: app.itachi-v2.local
      destinations: localhost:9001
management:
  endpoints:
    web:
      exposure:
        include: "*"
